i_owe_who/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/my_profile/', views.my_profile, name='my_profile'),
    path('accounts/send_friend_request/', views.send_friend_request, name='send_friend_request'),
    path('accounts/accept_friend_request/<int:user_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('accounts/cancel_friend_request/<int:user_id>/', views.cancel_friend_request, name='cancel_friend_request'),
    path('accounts/remove_friend/<int:user_id>/', views.remove_friend, name='remove_friend'),
    path('ledgers/', views.ledgers_index, name='ledgers_index'),
    path('ledgers/<int:ledger_id>/', views.ledgers_detail, name='ledgers_detail'),
    path('ledgers/create/', views.LedgerCreate.as_view(), name='ledgers_create'),
    path('ledgers/<int:pk>/update/', views.LedgerUpdate.as_view(), name='ledgers_update'),
    path('ledgers/<int:pk>/delete/', views.LedgerDelete.as_view(), name='ledgers_delete'),
    path('ledgers/<int:ledger_id>/add_expense/', views.add_expense, name='add_expense'),
    path('expenses/', views.expenses_index, name='expenses_index'),
    path('expenses/<int:expense_id>/', views.expenses_detail, name='expenses_detail'),
    path('expenses/<int:pk>/update/', views.ExpenseUpdate.as_view(), name='expenses_update'),
    path('expenses/<int:pk>/delete/', views.ExpenseDelete.as_view(), name='expenses_delete'),
    path('expenses/<int:expense_id>/add_photo/', views.add_photo, name='add_photo'),
    path('expenses/<int:expense_id>/delete_photo/<int:photo_id>/', views.delete_photo, name='delete_photo'),
    path('expenses/search/', views.expenses_search, name='expenses_search'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

CURRENCIES = (
    ('AUD', 'Australian Dollar - $'),
    ('CAD', 'Canadian Dollar - $'),
    ('EUR', 'Euro - €'),
    ('GBP', 'British Pound - £'),
    ('JPY', 'Japanese Yen - ¥'),
    ('NZD', 'New Zealand Dollar - $'),
    ('USD', 'United States Dollar - $'),
    ('OTH', 'Other Currency - $'),
)

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    invites_sent = models.ManyToManyField(User, blank=True, related_name='invites_rec')

    def __str__(self):
        return f"{self.user.username}'s Profile"


class Ledger(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=300, blank=True)
    currency = models.CharField(
        max_length=3,
        choices=CURRENCIES,
        default=CURRENCIES[0][0]
    )
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ledgers_created')
    members = models.ManyToManyField(User, blank=True, related_name='ledgers_joined')
    
    class Meta:
        ordering = ['-updated_at']

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ledgers_detail', kwargs={'ledger_id': self.id})
    
    def get_total_spent(self):
        return self.expense_set.aggregate(models.Sum('amount', default=0))['amount__sum']
    
    def get_individual_spent(self):
        # Create a list of users from: creator, members, and distinct users from expenses:
        users = ([self.creator] + 
                [member for member in self.members.all()] + 
                [User.objects.get(id=user['user']) for user in self.expense_set.order_by().values('user').distinct()])
        # Convert list to a set to avoid duplicates:
        users_set = set(users)
        
        # Initialize the list of individual amounts spent:
        individual_spent = []
        
        # Calculate the total amount spent by each user:
        for user in users_set:
            individual_spent.append({
                'name': user.username,
                'total': self.expense_set.filter(user=user).aggregate(models.Sum('amount', default=0))['amount__sum']
            })

        return individual_spent


class Expense(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateField()
    ledger = models.ForeignKey(Ledger, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        ordering = ['-date', '-created_at']

    def __str__(self):
        return f"{self.name} - {self.amount} {self.ledger.currency}"
    
    def get_absolute_url(self):
        return reverse('expenses_detail', kwargs={'expense_id': self.id})


class Photo(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    url = models.CharField(max_length=200)
    expense = models.ForeignKey(Expense, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for {self.expense.name} - @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Ledger, Expense

class LedgerForm(ModelForm):
    class Meta:
        model = Ledger
        fields = ['name', 'description', 'currency', 'members']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        creator = kwargs.pop('creator', None)
        super().__init__(*args, **kwargs)
        # Use the user's friends as the queryset for members:
        self.fields['members'].queryset = user.profile.friends.all()


class ExpenseForm(ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'amount', 'date']

main_app/views.py
import uuid
import os
import boto3
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Profile, Ledger, Expense, Photo
from .forms import LedgerForm, ExpenseForm

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        # Get the 3 most recently updated ledgers where current user is either the creator or a member:
        #  Note: ledgers are already ordered by the updated_at field in descending order by the model.
        ledgers = Ledger.objects.filter(Q(creator=request.user) | Q(members=request.user)).distinct()[:3]
        # Get the 5 most recently added expenses by the current user:
        expenses = Expense.objects.filter(user=request.user).order_by('-date', '-created_at')[:5]
        return render(request, 'home.html', {
            'ledgers': ledgers,
            'expenses': expenses
        })
    else:
        # If the user is not authenticated, render the home page without any context:
        return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # Create a 'user' form object using the data from the browser request:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # Add the new user to the database:
            user = form.save()
            # Log the user in to save them from having to login after signup:
            login(request, user)
            # Create a profile for the new user:
            Profile.objects.create(user=user)
            return redirect('home')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with a form:
    # No existing form for GET requests, so create one:
    if request.method == 'GET':
        form = UserCreationForm()
    context = { 'form': form, 'error_message': error_message }
    return render(request, 'registration/signup.html', context)


@login_required
def my_profile(request):
    return render(request, 'profiles/my_profile.html')


@login_required
def send_friend_request(request):
    receiver_username = request.POST.get('username')
    receiver = User.objects.filter(username=receiver_username).first()

    if receiver:
        # Case 1: user sends a request to themselves:
        if request.user == receiver:
            return render(request, 'profiles/my_profile.html', {
                'toast_message': 'Cannot send a friend request to yourself.',
            })
        # Case 2: receiver is already a friend:
        elif receiver in request.user.profile.friends.all():
            return render(request, 'profiles/my_profile.html', {
                'toast_message': 'You are already friends with',
                'username': receiver_username,
            })
        # Case 3: request already sent to receiver:
        elif receiver in request.user.profile.invites_sent.all():
            return render(request, 'profiles/my_profile.html', {
                'toast_message': 'You have already sent a friend request to',
                'username': receiver_username,
            })
        # Case 4: request already received from receiver:
        elif request.user in receiver.profile.invites_sent.all():
            return render(request, 'profiles/my_profile.html', {
                'toast_message': 'You have already received a friend request from',
                'username': receiver_username,
            })
        # Case 5: request is valid and can be sent:
        else:
            # Add the receiver to the sender's invites_sent list:
            request.user.profile.invites_sent.add(receiver)
            return render(request, 'profiles/my_profile.html', {
                'toast_message': 'Friend request sent to',
                'username': receiver_username,
            })
    else:
        # Case 6: the receiver does not exist:
        return render(request, 'profiles/my_profile.html', {
            'toast_message': 'Could not find user',
            'username': receiver_username,
        })


@login_required
def accept_friend_request(request, user_id):
    new_friend = User.objects.get(id=user_id)
    # Add new friend's user.id to logged in user's friends list:
    request.user.profile.friends.add(new_friend)
    # Add logged in user's user.id to new friend's friends list:
    new_friend.profile.friends.add(request.user)
    # Remove logged in user's user.id from new friend's invites_sent list:
    new_friend.profile.invites_sent.remove(request.user)

    return render(request, 'profiles/my_profile.html', {
        'toast_message': 'You are now friends with',
        'username': new_friend.username,
    })


@login_required
def cancel_friend_request(request, user_id):
    invitee = User.objects.get(id=user_id)
    # Remove invitee's user.id from logged in user's invites_sent list:
    request.user.profile.invites_sent.remove(invitee)
    
    return render(request, 'profiles/my_profile.html', {
        'toast_message': 'Retracted friend request to',
        'username': invitee.username,
    })


@login_required
def remove_friend(request, user_id):
    old_friend = User.objects.get(id=user_id)
    # Remove old_friend's user.id from logged in user's friends list:
    request.user.profile.friends.remove(old_friend)
    # Remove logged in user's user.id from old_friend's friends list:
    old_friend.profile.friends.remove(request.user)
    
    return render(request, 'profiles/my_profile.html', {
        'toast_message': 'You are no longer friends with',
        'username': old_friend.username,
    })


@login_required
def ledgers_index(request):
    # Get all ledgers where the current user is either the creator or a member:
    ledgers = Ledger.objects.filter(Q(creator=request.user) | Q(members=request.user)).distinct()
    return render(request, 'ledgers/index.html', {
        'ledgers': ledgers
    })


@login_required
def ledgers_detail(request, ledger_id):
    ledger = Ledger.objects.get(id=ledger_id)
    # Redirect back to index page if user is not the creator or a member of this ledger:
    if request.user != ledger.creator and request.user not in ledger.members.all():
        return redirect('ledgers_index')
    
    # Create an ExpenseForm instance to be used in the template:
    expense_form = ExpenseForm()
    return render(request, 'ledgers/detail.html', {
        'ledger': ledger,
        'expense_form': expense_form
    })


class LedgerCreate(LoginRequiredMixin, CreateView):
    model = Ledger
    form_class = LedgerForm

    # Override the inherited method called when a valid form is submitted:
    def form_valid(self, form):
        # Assign the logged in user (self.request.user) as the ledgers creator:
        form.instance.creator = self.request.user
        # Pass control back to the superclass CreateView's form_valid() method to do its job:
        return super().form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class LedgerUpdate(LoginRequiredMixin, UpdateView):
    model = Ledger
    form_class = LedgerForm

    # Redirect back to the ledger detail page if the user is not the creator:
    def get(self, request, *args, **kwargs):
        ledger = self.get_object()
        if request.user != ledger.creator:
            return redirect('ledgers_detail', ledger_id=ledger.id)
        return super().get(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Pass the logged in user to the form:
        kwargs['user'] = self.request.user
        # Pass the ledger's creator to the form:
        ledger = self.get_object()
        kwargs['creator'] = ledger.creator
        return kwargs


class LedgerDelete(LoginRequiredMixin, DeleteView):
    model = Ledger
    success_url = '/ledgers'

    # Redirect back to the ledger detail page if the user is not the creator:
    def get(self, request, *args, **kwargs):
        ledger = self.get_object()
        if request.user != ledger.creator:
            return redirect('ledgers_detail', ledger_id=ledger.id)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        # Get the ledger object to be deleted:
        ledger = self.get_object()
        # Set up the Amazon S3 variables:
        s3 = boto3.client('s3')
        bucket = os.environ['S3_BUCKET']
        # Loop through all expenses on the ledger and delete their photos from Amazon S3:
        for expense in ledger.expense_set.all():
            for photo in expense.photo_set.all():
                key = photo.url.split('/')[-1]
                # Use a try-except block to handle any errors that may occur:
                try:
                    # Delete the photo from S3 and our database:
                    s3.delete_object(Bucket=bucket, Key=key)
                    photo.delete()
                except Exception as e:
                    print('An error occurred deleting file from S3')
                    print(e)
        # Now call the superclass form_valid method to delete the expense:
        return super().form_valid(form)


@login_required
def expenses_index(request):
    # Get all expenses where the current user is the owner:
    expenses = Expense.objects.filter(user=request.user)
    return render(request, 'expenses/index.html', {
        'expenses': expenses
    })


@login_required
def expenses_detail(request, expense_id):
    expense = Expense.objects.get(id=expense_id)

main_app/templates/expenses/detail.html
{% extends 'base.html' %}
{% block content %}

<h3>Expense Details</h3>

<a 
  href="{% url 'ledgers_detail' expense.ledger.id %}"
  class="red-text nav-link"
>
  <i class="material-icons tiny">keyboard_backspace</i>
  Return to ledger
</a>

<div class="card grey darken-3">
  <div class="card-content">
    <span class="card-title">{{ expense.name }}</span>
    <p>Date: {{ expense.date|date:"Y-m-d D" }}</p>
    <p>Amount: {{ expense.ledger.get_currency_display|slice:"-1:" }}{{ expense.amount }}</p>
    <p>Paid by: {{ expense.user }}</p>
    <p class="grey-text">Created at: {{ expense.created_at|date:"Y-m-d g:i a" }}</p>
    <p class="grey-text">Updated at: {{ expense.updated_at|date:"Y-m-d g:i a" }}</p>
  </div>
  <div class="card-action">
    {% if user == expense.user or user == expense.ledger.creator %}
      <a href="{% url 'expenses_update' expense.id %}">Edit</a>
      <a href="{% url 'expenses_delete' expense.id %}">Delete</a>
    {% else %}
      <span class="grey-text"><em>Only the creator of the ledger or this expense can edit or delete.</em></span>
    {% endif %}
  </div>
</div>

<div class="card-panel photos-card">
{% for photo in expense.photo_set.all %}
  <div>
    <img
      src="{{ photo.url }}"
      alt="photo of {{ expense.name }}"
      class="responsive-img materialboxed"
    >
    <!-- Only render the remove photo button for the ledger creator and expense user -->
    {% if user == expense.user or user == expense.ledger.creator %}
      <button
        data-target="modal{{ forloop.counter }}"
        class="btn-small waves-effect waves-light modal-trigger"
      >
        Remove
      </button>
    {% endif %}
  </div>

  <!-- Only render the remove photo modal for the ledger creator and expense user -->
  {% if user == expense.user or user == expense.ledger.creator %}
    <div id="modal{{ forloop.counter }}" class="modal">
      <form action="{% url 'delete_photo' expense.id photo.id %}" method="POST">
        {% csrf_token %}
        <div class="modal-content">
          <h5>Delete Photo:<i class="small material-icons modal-close right">close</i></h5>
          <p>
            Are you sure you want delete this photo?
          </p>
        </div>
        <div class="modal-footer row">
          <button
            type="submit"
            class="btn waves-effect waves-light col s12">
            Yes - Delete
          </button>
        </div>
      </form>
    </div>
  {% endif %}

{% empty %}
  <span class="red-text">
    No photos uploaded.
  </span>
{% endfor %}
</div>

<!-- Only render the photo upload form for the ledger creator and expense user -->
{% if user == expense.user or user == expense.ledger.creator %}
  <form 
    action="{% url 'add_photo' expense.id %}"
    enctype="multipart/form-data"
    method="POST"
    class="card-panel row"
  >
    {% csrf_token %}
    <div class="file-field input-field">
      <div class="btn waves-effect waves-light">
        <span>File</span>
        <input type="file" name="photo-file" required>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>
    <button type="submit" class="btn waves-effect waves-light col s12">Upload Photo</button>
  </form>
{% endif %}

<script>
  const modalEls = document.querySelectorAll('.modal');
  M.Modal.init(modalEls);
  const elems = document.querySelectorAll('.materialboxed');
  M.Materialbox.init(elems);
</script>

{% endblock %}

main_app/templates/expenses/index.html
{% extends 'base.html' %}
{% block content %}

<h3>My Expenses</h3>

<ul class="collection">
  {% for expense in expenses.all %}
    <!-- The Modal for each expense -->
    <div id="modal{{ forloop.counter }}" class="modal expense-modal">
      <div class="modal-content">
        <h5>Expense Details:<i class="small material-icons modal-close right">close</i></h5>
        <p>Name: {{ expense.name }}</p>
        <p>Date: {{ expense.date|date:"Y-m-d" }}</p>
        <p>Amount: {{ expense.ledger.get_currency_display|slice:"-1:" }}{{ expense.amount }}</p>
        <p>Ledger: {{ expense.ledger.name }}</p>
        <p>Photo added: {{ expense.photo_set.count|yesno:"Yes,No" }}</p>
        <p class="grey-text">Created at: {{ expense.created_at|date:"Y-m-d g:i a" }}</p>
        <p class="grey-text">Updated at: {{ expense.updated_at|date:"Y-m-d g:i a" }}</p>
      </div>
      <div class="modal-footer double">
        <a
          href="{% url 'ledgers_detail' expense.ledger.id %}"
          class="btn btn2 waves-effect waves-light col s12">
          View Ledger
        </a>
        <a
          href="{% url 'expenses_detail' expense.id %}"
          class="btn waves-effect waves-light col s12">
          View Expense
        </a>
      </div>
    </div>
    <!-- The collection-item for each expense -->
    <li class="collection-item avatar hoverable">
      <a class="modal-trigger" href="#modal{{ forloop.counter }}">
        <span class="expense-amount">{{ expense.ledger.get_currency_display|slice:"-1:" }}{{ expense.amount }}</span>
        <p class="title truncate">{{ expense.name }}</p>
        <p class="truncate">
          Date: {{ expense.date|date:"Y-m-d" }} <br>
          Ledger: {{ expense.ledger.name }}
        </p>
      </a>
    </li>
  {% empty %}
    <li class="collection-item">
      <p class="title">No expenses added yet.</p>
    </li>
  {% endfor %}
</ul>

<script>
  const modalEls = document.querySelectorAll('.expense-modal');
  M.Modal.init(modalEls);
</script>

{% endblock %}

main_app/templates/expenses/search.html
{% extends 'base.html' %}
{% block content %}

<h3>Search Results</h3>

<p>
  Search term: {{ search_term }}
</p>

<form method="GET" action="{% url 'expenses_search' %}">
  <div class="input-field edit-search">
    <input id="edit-search" type="search" name="term" required value="{{ search_term }}">
    <label class="label-icon" for="edit-search"><i class="material-icons">search</i></label>
    <i class="material-icons">close</i>
  </div>
</form>

<ul class="collection">
  {% for expense in expenses.all %}
    <!-- The Modal for each expense -->
    <div id="modal{{ forloop.counter }}" class="modal expense-modal">
      <div class="modal-content">
        <h5>Expense Details:<i class="small material-icons modal-close right">close</i></h5>
        <p>Name: {{ expense.name }}</p>
        <p>Date: {{ expense.date|date:"Y-m-d" }}</p>
        <p>Amount: {{ expense.ledger.get_currency_display|slice:"-1:" }}{{ expense.amount }}</p>
        <p>Ledger: {{ expense.ledger.name }}</p>
        <p>Photo added: {{ expense.photo_set.count|yesno:"Yes,No" }}</p>
        <p class="grey-text">Created at: {{ expense.created_at|date:"Y-m-d g:i a" }}</p>
        <p class="grey-text">Updated at: {{ expense.updated_at|date:"Y-m-d g:i a" }}</p>
      </div>
      <div class="modal-footer double">
        <a
          href="{% url 'ledgers_detail' expense.ledger.id %}"
          class="btn btn2 waves-effect waves-light col s12">
          View Ledger
        </a>
        <a
          href="{% url 'expenses_detail' expense.id %}"
          class="btn waves-effect waves-light col s12">
          View Expense
        </a>
      </div>
    </div>
    <!-- The collection-item for each expense -->
    <li class="collection-item avatar hoverable">
      <a class="modal-trigger" href="#modal{{ forloop.counter }}">
        <span class="expense-amount">{{ expense.ledger.get_currency_display|slice:"-1:" }}{{ expense.amount }}</span>
        <p class="title truncate">{{ expense.name }}</p>
        <p class="truncate">
          Date: {{ expense.date|date:"Y-m-d" }} <br>
          Ledger: {{ expense.ledger.name }}
        </p>
      </a>
    </li>
  {% empty %}
    <li class="collection-item">
      <p class="title"><em>No results for "{{ search_term }}".</em></p>
    </li>
  {% endfor %}
</ul>

<script>
  const modalEls = document.querySelectorAll('.expense-modal');
  M.Modal.init(modalEls);
</script>

{% endblock %}